#!/usr/bin/env python3

from datetime import datetime
from .features import *
import warnings

class FeatureExtractor(object):
    def __init__(self, floating_point_unit: str):
        warnings.filterwarnings("ignore")

        self.floating_point_unit = floating_point_unit
        self.__features = [
                Duration(),
                PacketsCount(),
                FwdPacketsCount(),
                BwdPacketsCount(),

                TotalPayloadBytes(),
                FwdTotalPayloadBytes(),
                BwdTotalPayloadBytes(),
                PayloadBytesMax(),
                PayloadBytesMin(),
                PayloadBytesMean(),
                PayloadBytesStd(),
                PayloadBytesVariance(),
                PayloadBytesMedian(),
                PayloadBytesSkewness(),
                PayloadBytesCov(),
                PayloadBytesMode(),
                FwdPayloadBytesMax(),
                FwdPayloadBytesMin(),
                FwdPayloadBytesMean(),
                FwdPayloadBytesStd(),
                FwdPayloadBytesVariance(),
                FwdPayloadBytesMedian(),
                FwdPayloadBytesSkewness(),
                FwdPayloadBytesCov(),
                FwdPayloadBytesMode(),
                BwdPayloadBytesMax(),
                BwdPayloadBytesMin(),
                BwdPayloadBytesMean(),
                BwdPayloadBytesStd(),
                BwdPayloadBytesVariance(),
                BwdPayloadBytesMedian(),
                BwdPayloadBytesSkewness(),
                BwdPayloadBytesCov(),
                BwdPayloadBytesMode(),

                TotalHeaderBytes(),
                MaxHeaderBytes(),
                MinHeaderBytes(),
                MeanHeaderBytes(),
                StdHeaderBytes(),
                MedianHeaderBytes(),
                SkewnessHeaderBytes(),
                CoVHeaderBytes(),
                ModeHeaderBytes(),
                VarianceHeaderBytes(),
                FwdTotalHeaderBytes(),
                FwdMaxHeaderBytes(),
                FwdMinHeaderBytes(),
                FwdMeanHeaderBytes(),
                FwdStdHeaderBytes(),
                FwdMedianHeaderBytes(),
                FwdSkewnessHeaderBytes(),
                FwdCoVHeaderBytes(),
                FwdModeHeaderBytes(),
                FwdVarianceHeaderBytes(),
                BwdTotalHeaderBytes(),
                BwdMaxHeaderBytes(),
                BwdMinHeaderBytes(),
                BwdMeanHeaderBytes(),
                BwdStdHeaderBytes(),
                BwdMedianHeaderBytes(),
                BwdSkewnessHeaderBytes(),
                BwdCoVHeaderBytes(),
                BwdModeHeaderBytes(),
                BwdVarianceHeaderBytes(),

                FwdSegmentSizeMean(),
                FwdSegmentSizeMax(),
                FwdSegmentSizeMin(),
                FwdSegmentSizeStd(),
                FwdSegmentSizeVariance(),
                FwdSegmentSizeMedian(),
                FwdSegmentSizeSkewness(),
                FwdSegmentSizeCov(),
                FwdSegmentSizeMode(),
                BwdSegmentSizeMean(),
                BwdSegmentSizeMax(),
                BwdSegmentSizeMin(),
                BwdSegmentSizeStd(),
                BwdSegmentSizeVariance(),
                BwdSegmentSizeMedian(),
                BwdSegmentSizeSkewness(),
                BwdSegmentSizeCov(),
                BwdSegmentSizeMode(),
                SegmentSizeMean(),
                SegmentSizeMax(),
                SegmentSizeMin(),
                SegmentSizeStd(),
                SegmentSizeVariance(),
                SegmentSizeMedian(),
                SegmentSizeSkewness(),
                SegmentSizeCov(),
                SegmentSizeMode(),

                FwdInitWinBytes(),
                BwdInitWinBytes(),

                ActiveMin(),
                ActiveMax(),
                ActiveMean(),
                ActiveStd(),
                ActiveMedian(),
                ActiveSkewness(),
                ActiveCoV(),
                ActiveMode(),
                ActiveVariance(),

                IdleMin(),
                IdleMax(),
                IdleMean(),
                IdleStd(),
                IdleMedian(),
                IdleSkewness(),
                IdleCoV(),
                IdleMode(),
                IdleVariance(),

                BytesRate(),
                FwdBytesRate(),
                BwdBytesRate(),
                PacketsRate(),
                BwdPacketsRate(),
                FwdPacketsRate(),
                DownUpRate(),

                AvgFwdBytesPerBulk(),
                AvgFwdPacketsPerBulk(),
                AvgFwdBulkRate(),
                AvgBwdBytesPerBulk(),
                AvgBwdPacketsPerBulk(),
                AvgBwdBulkRate(),
                FwdBulkStateCount(),
                FwdBulkSizeTotal(),
                FwdBulkPacketCount(),
                FwdBulkDuration(),
                BwdBulkStateCount(),
                BwdBulkSizeTotal(),
                BwdBulkPacketCount(),
                BwdBulkDuration(),

                FINFlagCounts(),
                PSHFlagCounts(),
                URGFlagCounts(),
                ECEFlagCounts(),
                SYNFlagCounts(),
                ACKFlagCounts(),
                CWRFlagCounts(),
                RSTFlagCounts(),
                FwdFINFlagCounts(),
                FwdPSHFlagCounts(),
                FwdURGFlagCounts(),
                FwdECEFlagCounts(),
                FwdSYNFlagCounts(),
                FwdACKFlagCounts(),
                FwdCWRFlagCounts(),
                FwdRSTFlagCounts(),
                BwdFINFlagCounts(),
                BwdPSHFlagCounts(),
                BwdURGFlagCounts(),
                BwdECEFlagCounts(),
                BwdSYNFlagCounts(),
                BwdACKFlagCounts(),
                BwdCWRFlagCounts(),
                BwdRSTFlagCounts(),

                FINFlagPercentageInTotal(),
                PSHFlagPercentageInTotal(),
                URGFlagPercentageInTotal(),
                ECEFlagPercentageInTotal(),
                SYNFlagPercentageInTotal(),
                ACKFlagPercentageInTotal(),
                CWRFlagPercentageInTotal(),
                RSTFlagPercentageInTotal(),
                FwdFINFlagPercentageInTotal(),
                FwdPSHFlagPercentageInTotal(),
                FwdURGFlagPercentageInTotal(),
                FwdECEFlagPercentageInTotal(),
                FwdSYNFlagPercentageInTotal(),
                FwdACKFlagPercentageInTotal(),
                FwdCWRFlagPercentageInTotal(),
                FwdRSTFlagPercentageInTotal(),
                BwdFINFlagPercentageInTotal(),
                BwdPSHFlagPercentageInTotal(),
                BwdURGFlagPercentageInTotal(),
                BwdECEFlagPercentageInTotal(),
                BwdSYNFlagPercentageInTotal(),
                BwdACKFlagPercentageInTotal(),
                BwdCWRFlagPercentageInTotal(),
                BwdRSTFlagPercentageInTotal(),
                FwdFINFlagPercentageInFwdPackets(),
                FwdPSHFlagPercentageInFwdPackets(),
                FwdURGFlagPercentageInFwdPackets(),
                FwdECEFlagPercentageInFwdPackets(),
                FwdSYNFlagPercentageInFwdPackets(),
                FwdACKFlagPercentageInFwdPackets(),
                FwdCWRFlagPercentageInFwdPackets(),
                FwdRSTFlagPercentageInFwdPackets(),
                BwdFINFlagPercentageInBwdPackets(),
                BwdPSHFlagPercentageInBwdPackets(),
                BwdURGFlagPercentageInBwdPackets(),
                BwdECEFlagPercentageInBwdPackets(),
                BwdSYNFlagPercentageInBwdPackets(),
                BwdACKFlagPercentageInBwdPackets(),
                BwdCWRFlagPercentageInBwdPackets(),
                BwdRSTFlagPercentageInBwdPackets(),

                PacketsIATMean(),
                PacketsIATStd(),
                PacketsIATMax(),
                PacketsIATMin(),
                PacketsIATSum(),
                PacketsIATMedian(),
                PacketsIATSkewness(),
                PacketsIATCoV(),
                PacketsIATMode(),
                PacketsIATVariance(),
                FwdPacketsIATMean(),
                FwdPacketsIATStd(),
                FwdPacketsIATMax(),
                FwdPacketsIATMin(),
                FwdPacketsIATSum(),
                FwdPacketsIATMedian(),
                FwdPacketsIATSkewness(),
                FwdPacketsIATCoV(),
                FwdPacketsIATMode(),
                FwdPacketsIATVariance(),
                BwdPacketsIATMean(),
                BwdPacketsIATStd(),
                BwdPacketsIATMax(),
                BwdPacketsIATMin(),
                BwdPacketsIATSum(),
                BwdPacketsIATMedian(),
                BwdPacketsIATSkewness(),
                BwdPacketsIATCoV(),
                BwdPacketsIATMode(),
                BwdPacketsIATVariance(),

                SubflowFwdPackets(),
                SubflowBwdPackets(),
                SubflowFwdBytes(),
                SubflowBwdBytes(),

                DeltaStart(),
                HandshakeDuration(),
                HandshakeState(),

                PacketsDeltaTimeMin(),
                PacketsDeltaTimeMax(),
                PacketsDeltaTimeMean(),
                PacketsDeltaTimeMode(),
                PacketsDeltaTimeVariance(),
                PacketsDeltaTimeStd(),
                PacketsDeltaTimeMedian(),
                PacketsDeltaTimeSkewness(),
                PacketsDeltaTimeCoV(),
                BwdPacketsDeltaTimeMin(),
                BwdPacketsDeltaTimeMax(),
                BwdPacketsDeltaTimeMean(),
                BwdPacketsDeltaTimeMode(),
                BwdPacketsDeltaTimeVariance(),
                BwdPacketsDeltaTimeStd(),
                BwdPacketsDeltaTimeMedian(),
                BwdPacketsDeltaTimeSkewness(),
                BwdPacketsDeltaTimeCoV(),
                FwdPacketsDeltaTimeMin(),
                FwdPacketsDeltaTimeMax(),
                FwdPacketsDeltaTimeMean(),
                FwdPacketsDeltaTimeMode(),
                FwdPacketsDeltaTimeVariance(),
                FwdPacketsDeltaTimeStd(),
                FwdPacketsDeltaTimeMedian(),
                FwdPacketsDeltaTimeSkewness(),
                FwdPacketsDeltaTimeCoV(),

                PacketsDeltaLenMin(),
                PacketsDeltaLenMax(),
                PacketsDeltaLenMean(),
                PacketsDeltaLenMode(),
                PacketsDeltaLenVariance(),
                PacketsDeltaLenStd(),
                PacketsDeltaLenMedian(),
                PacketsDeltaLenSkewness(),
                PacketsDeltaLenCoV(),
                BwdPacketsDeltaLenMin(),
                BwdPacketsDeltaLenMax(),
                BwdPacketsDeltaLenMean(),
                BwdPacketsDeltaLenMode(),
                BwdPacketsDeltaLenVariance(),
                BwdPacketsDeltaLenStd(),
                BwdPacketsDeltaLenMedian(),
                BwdPacketsDeltaLenSkewness(),
                BwdPacketsDeltaLenCoV(),
                FwdPacketsDeltaLenMin(),
                FwdPacketsDeltaLenMax(),
                FwdPacketsDeltaLenMean(),
                FwdPacketsDeltaLenMode(),
                FwdPacketsDeltaLenVariance(),
                FwdPacketsDeltaLenStd(),
                FwdPacketsDeltaLenMedian(),
                FwdPacketsDeltaLenSkewness(),
                FwdPacketsDeltaLenCoV(),

                HeaderBytesDeltaLenMin(),
                HeaderBytesDeltaLenMax(),
                HeaderBytesDeltaLenMean(),
                HeaderBytesDeltaLenMode(),
                HeaderBytesDeltaLenVariance(),
                HeaderBytesDeltaLenStd(),
                HeaderBytesDeltaLenMedian(),
                HeaderBytesDeltaLenSkewness(),
                HeaderBytesDeltaLenCoV(),
                BwdHeaderBytesDeltaLenMin(),
                BwdHeaderBytesDeltaLenMax(),
                BwdHeaderBytesDeltaLenMean(),
                BwdHeaderBytesDeltaLenMode(),
                BwdHeaderBytesDeltaLenVariance(),
                BwdHeaderBytesDeltaLenStd(),
                BwdHeaderBytesDeltaLenMedian(),
                BwdHeaderBytesDeltaLenSkewness(),
                BwdHeaderBytesDeltaLenCoV(),
                FwdHeaderBytesDeltaLenMin(),
                FwdHeaderBytesDeltaLenMax(),
                FwdHeaderBytesDeltaLenMean(),
                FwdHeaderBytesDeltaLenMode(),
                FwdHeaderBytesDeltaLenVariance(),
                FwdHeaderBytesDeltaLenStd(),
                FwdHeaderBytesDeltaLenMedian(),
                FwdHeaderBytesDeltaLenSkewness(),
                FwdHeaderBytesDeltaLenCoV(),

                PayloadBytesDeltaLenMin(),
                PayloadBytesDeltaLenMax(),
                PayloadBytesDeltaLenMean(),
                PayloadBytesDeltaLenMode(),
                PayloadBytesDeltaLenVariance(),
                PayloadBytesDeltaLenStd(),
                PayloadBytesDeltaLenMedian(),
                PayloadBytesDeltaLenSkewness(),
                PayloadBytesDeltaLenCoV(),
                BwdPayloadBytesDeltaLenMin(),
                BwdPayloadBytesDeltaLenMax(),
                BwdPayloadBytesDeltaLenMean(),
                BwdPayloadBytesDeltaLenMode(),
                BwdPayloadBytesDeltaLenVariance(),
                BwdPayloadBytesDeltaLenStd(),
                BwdPayloadBytesDeltaLenMedian(),
                BwdPayloadBytesDeltaLenSkewness(),
                BwdPayloadBytesDeltaLenCoV(),
                FwdPayloadBytesDeltaLenMin(),
                FwdPayloadBytesDeltaLenMax(),
                FwdPayloadBytesDeltaLenMean(),
                FwdPayloadBytesDeltaLenMode(),
                FwdPayloadBytesDeltaLenVariance(),
                FwdPayloadBytesDeltaLenStd(),
                FwdPayloadBytesDeltaLenMedian(),
                FwdPayloadBytesDeltaLenSkewness(),
                FwdPayloadBytesDeltaLenCoV(),
                
                BINMinEntropy(),
                HEXMinEntropy(),
                UTF8MinEntropy(),

                #UTF84MaxEntropy(),
                #UTF88MaxEntropy(),
                #UTF816MaxEntropy(),
                #UTF832MaxEntropy(),
                #UTF864MaxEntropy(),

                #HEX4MaxEntropy(),
                #HEX8MaxEntropy(),
                #HEX16MaxEntropy(),
                #HEX32MaxEntropy(),
                #HEX64MaxEntropy(),

                #BIN4MaxEntropy(),
                #BIN8MaxEntropy(),
                #BIN16MaxEntropy(),
                #BIN32MaxEntropy(),
                #BIN64MaxEntropy(),

                #BIN4CollisionEntropy(),
                #BIN8CollisionEntropy(),
                #BIN16CollisionEntropy(),
                #BIN32CollisionEntropy(),
                #BIN64CollisionEntropy(),

                #HEX4CollisionEntropy(),
                #HEX8CollisionEntropy(),
                #HEX16CollisionEntropy(),
                #HEX32CollisionEntropy(),
                #HEX64CollisionEntropy(),

                #UTF84CollisionEntropy(),
                #UTF88CollisionEntropy(),
                #UTF816CollisionEntropy(),
                #UTF832CollisionEntropy(),
                #UTF864CollisionEntropy(),

                Bi16Entropy(),
                Bi32Entropy(),

                MEANMutualInformation(),
                MODEMutualInformation(),
                STDMutualInformation(),
                MEDIANMutualInformation(),
                COVMutualInformation(),
                SKEWNESSMutualInformation(),
                
                MEAN4Entropy(),
                STD4Entropy(),
                SKEWNESS4Entropy(),
                MODE4Entropy(),
                MEDIAN4Entropy(),
                COV4Entropy(),

                MEAN8Entropy(),
                STD8Entropy(),
                SKEWNESS8Entropy(),
                MODE8Entropy(),
                MEDIAN8Entropy(),
                COV8Entropy(),

                MEAN16Entropy(),
                STD16Entropy(),
                SKEWNESS16Entropy(),
                MODE16Entropy(),
                MEDIAN16Entropy(),
                COV16Entropy(),

                MEAN16Entropy(),
                STD16Entropy(),
                SKEWNESS16Entropy(),
                MODE16Entropy(),
                MEDIAN16Entropy(),
                COV16Entropy(),

                MEAN32Entropy(),
                STD32Entropy(),
                SKEWNESS32Entropy(),
                MODE32Entropy(),
                MEDIAN32Entropy(),
                COV32Entropy(),

                MEAN64Entropy(),
                STD64Entropy(),
                SKEWNESS64Entropy(),
                MODE64Entropy(),
                MEDIAN64Entropy(),
                COV64Entropy(),

                MEAN4HEXEntropy(),
                STD4HEXEntropy(),
                SKEWNESS4HEXEntropy(),
                MODE4HEXEntropy(),
                MEDIAN4HEXEntropy(),
                COV4HEXEntropy(),

                MEAN8HEXEntropy(),
                STD8HEXEntropy(),
                SKEWNESS8HEXEntropy(),
                MODE8HEXEntropy(),
                MEDIAN8HEXEntropy(),
                COV8HEXEntropy(),

                MEAN16HEXEntropy(),
                STD16HEXEntropy(),
                SKEWNESS16HEXEntropy(),
                MODE16HEXEntropy(),
                MEDIAN16HEXEntropy(),
                COV16HEXEntropy(),

                MEAN32HEXEntropy(),
                STD32HEXEntropy(),
                SKEWNESS32HEXEntropy(),
                MODE32HEXEntropy(),
                MEDIAN32HEXEntropy(),
                COV32HEXEntropy(),

                MEAN64HEXEntropy(),
                STD64HEXEntropy(),
                SKEWNESS64HEXEntropy(),
                MODE64HEXEntropy(),
                MEDIAN64HEXEntropy(),
                COV64HEXEntropy(),

                MEAN4UTF8Entropy(),
                STD4UTF8Entropy(),
                SKEWNESS4UTF8Entropy(),
                MODE4UTF8Entropy(),
                MEDIAN4UTF8Entropy(),
                COV4UTF8Entropy(),

                MEAN8UTF8Entropy(),
                STD8UTF8Entropy(),
                SKEWNESS8UTF8Entropy(),
                MODE8UTF8Entropy(),
                MEDIAN8UTF8Entropy(),
                COV8UTF8Entropy(),

                MEAN16UTF8Entropy(),
                STD16UTF8Entropy(),
                SKEWNESS16UTF8Entropy(),
                MODE16UTF8Entropy(),
                MEDIAN16UTF8Entropy(),
                COV16UTF8Entropy(),

                MEAN32UTF8Entropy(),
                STD32UTF8Entropy(),
                SKEWNESS32UTF8Entropy(),
                MODE32UTF8Entropy(),
                MEDIAN32UTF8Entropy(),
                COV32UTF8Entropy(),

                MEAN64UTF8Entropy(),
                STD64UTF8Entropy(),
                SKEWNESS64UTF8Entropy(),
                MODE64UTF8Entropy(),
                MEDIAN64UTF8Entropy(),
                COV64UTF8Entropy(),

                BIN2GramEntropy(),
                BIN3GramEntropy(),
                BIN4GramEntropy(),
                BIN5GramEntropy(),
                BIN6GramEntropy(),
                BIN7GramEntropy(),
                BIN8GramEntropy(),
                BIN9GramEntropy(),
                BIN10GramEntropy(),
            
                HEX2GramEntropy(),
                HEX3GramEntropy(),
                HEX4GramEntropy(),
                HEX5GramEntropy(),
                HEX6GramEntropy(),
                HEX7GramEntropy(),
                HEX8GramEntropy(),
                HEX9GramEntropy(),
                HEX10GramEntropy(),

                UTF82GramEntropy(),
                UTF83GramEntropy(),
                UTF84GramEntropy(),
                UTF85GramEntropy(),
                UTF86GramEntropy(),
                UTF87GramEntropy(),
                UTF88GramEntropy(),
                UTF89GramEntropy(),
                UTF810GramEntropy(),
            ]

    def execute(self, data: list, data_lock, flows: List[Flow], features_ignore_list: list = [],
            label: str = "") -> list:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")

            self.__extracted_data = []
            for flow in flows:
                features_of_flow = {}
                features_of_flow["flow_id"] = str(flow)
                features_of_flow["timestamp"] = datetime.fromtimestamp(float(flow.get_timestamp()))
                features_of_flow["src_ip"] = flow.get_src_ip()
                features_of_flow["src_port"] = flow.get_src_port()
                features_of_flow["dst_ip"] = flow.get_dst_ip()
                features_of_flow["dst_port"] = flow.get_dst_port()
                features_of_flow["protocol"] = flow.get_protocol()
                feature: Feature
                for feature in self.__features:
                    if feature.name in features_ignore_list:
                        continue
                    feature.set_floating_point_unit(self.floating_point_unit)
                    try:
                        features_of_flow[feature.name] = feature.extract(flow)
                    except Exception as e:
                        print(f">>> Error occured in extracting the '{feature.name}' for '{flow}' flow.")
                        print(f">>> Error message: {e}")
                        print(110*"=")
                        features_of_flow[feature.name] = None
                        continue
                features_of_flow["label"] = label
                self.__extracted_data.append(features_of_flow.copy())
                # print(len(features_of_flow))
            with data_lock:
                data.extend(self.__extracted_data)
